language: java

jdk:
  - oraclejdk8

install: mvn install -DskipTests=true -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true -B -V

script: mvn test -B

cache:
  directories:
    - $HOME/.m2/repository/
